### ISSUE TITLE
course questions

### ISSUE THREAD

**Issue by owiofwm2i** [atredis-jordan/SymbolicExecutionCourseSample#1]
Hello
Is this a paid course? Or its a  free training, where can see the specific content?
thank you

**Comment by atredis-jordan** [comment]
Hello! This is a sample from a paid course we give.
We have two public instances of the class coming up, if you are interested.

In Person:
https://sectrain.hitb.org/courses/practical-symbolic-execution-for-vr-and-re-hitb2023ams/

Virtual Only:
https://ringzer0.training/trainings/practical-symbolic-execution-for-vr-and-re.html
